= Milestone 2: Requirements
Benno Bielmeier <benno.bielmeier@st.oth-regensburg.de>
:lang: en
:icons: font

[NOTE]
====
The keywords "`MUST`", "`MUST NOT`", "`REQUIRED`", "`SHALL`", "`SHALL NOT`", "`SHOULD`", "`SHOULD NOT`", "`RECOMMENDED`", "`MAY`", and "`OPTIONAL`" in this document are to be interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC 2119].
====

.Architecture
* [x] _MUST_ separate between front-end and back-end.
_SHOULD_ be separated by different packages.
_MAY_ be separated by different deployment components
* [x] _MUST_ apply layer architecture (presentation, business logic, persistence).
* [x] User-web-interface _MUST_ be realized with the MVC pattern.

.Dependency Injection (DI) / Inversion of Control (IoC)
* [x] Connecting the classes of different components _MUST_ be realized via DI / IoC (`@Autowired`).
* [x] Application _MUST_ contain at least one custom producer method for bean creation.
This method _MUST_ be used. +
__-> e.g. injected `HttpHeaders` provided by producer methods in link:../main/java/de/othr/bib48218/chat/integration/PartnerServiceConfig.java[`PartnerServiceConfiguration`] that are used in link:../main/java/de/othr/bib48218/chat/rest/[REST controllers]__
* [ ] Each CDI bean _MUST_ have an appropriate scope.

.Persistence
* [x] Database access _MUST_ only be done via spring persistence (entities and repositories). +
__-> only exception: insertion of required service bot users after database creation in link:../main/resources/import.sql[`import.sql`]__
* [x] It _MUST NOT_ access a database directly via JDBC and native SQL.
* [ ] Embeddables _SHOULD_ be used.
* [x] Cascading _SHOULD_ be used at least once.
Purpose _MUST_ be understood. +
__-> e.g. in link:../main/java/de/othr/bib48218/chat/entity/User.java[`User`] class__
* [x] OrphanRemoval _SHOULD_ be used at least once.
Purpose _MUST_ be understood. +
__-> e.g. in link:../main/java/de/othr/bib48218/chat/entity/User.java[`User`] class__
* [x] CRUD repositories _MUST_ be used.
* [ ] JPA repositories _SHOULD_ be used.
* [x] PagingAndSorting repositories _SHOULD_ be used. +
__-> link:../main/java/de/othr/bib48218/chat/repository/MessageRepository.java[`MessageRepository`]__
* [x] Inheritance mapping _MAY_ be used. +
__-> link:../main/java/de/othr/bib48218/chat/entity/Person.java[`Person`] and link:../main/java/de/othr/bib48218/chat/entity/Bot.java[`Bot`] extends link:../main/java/de/othr/bib48218/chat/entity/User.java[`User`]__ +
__-> link:../main/java/de/othr/bib48218/chat/entity/PeerChat.java[`PeerChat`] and link:../main/java/de/othr/bib48218/chat/entity/GroupChat.java[`GroupChat`] extends link:../main/java/de/othr/bib48218/chat/entity/Chat.java[`Chat`]__ +
__-> link:../main/java/de/othr/bib48218/chat/entity/UserProfile.java[`UserProfile`] and link:../main/java/de/othr/bib48218/chat/entity/ChatProfile.java[`ChatProfile`] extends link:../main/java/de/othr/bib48218/chat/entity/Profile.java[`Profile`]__
* [x] MappedSuperclass _SHOULD_ be used.
Purpose _MUST_ be understood. +
__-> link:../main/java/de/othr/bib48218/chat/entity/IdEntity.java[`IdEntity`]__

.Web UI
* [x] UI _MUST_ be realized via Spring-MVC.
* [x] Thymeleaf _MUST_ be used as rendering library.
* [x] View fragmentation and re-usage _SHOULD_ be used. +
__see fragments in link:../main/resources/templates/fragment/[`templates/fragment/`]__
* [x] https://getbootstrap.com[Bootstrap] _SHOULD_ be used.

.Repository
* [x] Write access _MUST_ be done in transactional context.
.. Therefore, service classes _MUST_ be annotated with `@Transactional` with an appropriate transaction type.

.Integration
* [x] One service class _MUST_ be public accessible for a partner project.
At least one method _MUST_ be callable. +
__-> link:../main/java/de/othr/bib48218/chat/service/IFSendMessage.java[`IFSendMessage`]__
* [x] At least one service method provided by a foreign service _MUST_ be called.
Service method(s) _SHOULD_ be used internally. +
__-> foreign service `TransferServiceExternalIF` is called in link:../main/java/de/othr/bib48218/chat/service/PaymentService.java[`PaymentService`] and internally used in link:../main/java/de/othr/bib48218/chat/integration/PaymentEventSubscriber.java[`PaymentEventSubscriber`]__
* [x] Integration _MUST_ be realized either with RESTful web service or asynchronous messaging (queues or topics). +
__-> RESTful usage in link:../main/java/de/othr/bib48218/chat/service/PaymentService.java[`PaymentService`]__
* [x] RESTful paths _MUST_ be intuitive.

.Deployment
* [x] Application _MUST_ be deployed on lab server.
* [x] Application with all its source code and configuration files (but without any binaries) _MUST_ be uploaded to G.R.I.P.S. as one ZIP file.

.Usage of foreign sources
* [x] Project _MUST_ be realized individually.
* [ ] Project _MAY_ re-use some small parts of foreign source code.
If so, the origin of the source code _MUST_ be stated in the comments.
The inclusion of foreign code _MUST NOT_ fulfill essential requirements of the application.
* [x] Additional dependencies _MAY_ be used.
If so, they _MUST_ be imported via Maven. +
__-> see link:../../pom.xml[`pom.xml`]__
