@startuml chat-usecase
skinparam monochrome true
left to right direction

' actors
actor User
actor Person
' note "Bot has no special usecases" as b
node "Partner Service" as Service

' actor hierarchy
User <|-left- Person

' use cases
package "de.othr.st.bib48218.chat" {
  Person --> (Login    user)
  Person --> (Logout   user)
  Person --> (Register user)

  Person --> (View   user profile)
  Person --> (Change user profile)
  Person --> (Change profile of group chat)

  User    --> (Send message)
  Service --> (Send message) 
  
  User   --> (Leave  group chat)
  Person --> (Create group chat)

  User --> (Change group chat membership of user)

  ' Connecting to partners use cases
  Person --> (Store foreign service account credential)
}
@enduml
