@startuml chat-usecase
skinparam monochrome true
left to right direction

' actors
actor "User" as u
actor "Person" as p
actor "Bot" as b
node "Service" as s

' actor hierarchy
p -down-|> u
b -down-|> u

' use cases
package "de.othr.st.bib48218.chat" {
  usecase "Login" as oUC1
  usecase "Logout" as oUC2
  usecase "Register" as oUC3
  usecase "Change profile image" as oUC4
  usecase "Change profile name" as oUC5
  usecase "Change profile" as oeUC1
  oUC4 ..> oeUC1 : extends
  oUC5 ..> oeUC1 : extends

  usecase "Send message" as mUC
  ' Chating use cases
  usecase "Join chat" as cUC1
  usecase "Leave chat" as cUC2
  usecase "Change chat membership" as ceUC2
  usecase "Change chat image" as cUC3
  usecase "Change chat description" as cUC4
  usecase "Chage chat information" as ceUC1
  cUC1 ..> ceUC2 : extends
  cUC2 ..> ceUC2 : extends
  cUC3 ..> ceUC1 : extends
  cUC4 ..> ceUC1 : extends
  ' Connecting to partners use cases
  usecase "Connect to (partner) service" as pUC
}

'  link actor User with use cases
p --> oUC1
p --> oUC2
p --> oUC3
u --> oUC4
u --> oUC5
s --> mUC
u --> mUC
u --> cUC1
u --> cUC2
u --> cUC3
u --> cUC4
u --> pUC
@enduml
