@startuml chat-domain
' classes in alphabetical order
class Attachment {
    size : int
    name : String
    mime_type : String
}

abstract class Chat

class ChatMembership

enum ChatMemberStatus <<enumeration>> {
    Administrator
    Member
    Restricted
    Left
    Kicked
}

class ChatProfile {
    description : String
}

class GroupChat

enum GroupVisibility <<enumeration>> {
    Private
    Public
}

class ServiceCredentials {
    login_token : String
}

class Message {
    text : String
    timestamp : Datetime
}

class Person {
    first_name : String
    last_name : String
    email : String
}

class PeerChat

abstract class Profile {
    name : String
    photo : image
}

enum ServiceType <<enumeration>> {
    Webshop
    Bank
    Payment
}

abstract class User {
    username : String
    password : String
}

class UserProfile {
    bio : String
    country : String
}

' Inheritance
'' Profile
Profile <|-- ChatProfile
Profile <|-- UserProfile
'' Chat inheritance
Chat <|-- PeerChat
Chat <|-- GroupChat

'' Person inheritance
User <|-- Person
User <|-- Bot

' Relations
'' to Chat
User "1" --> "0..*" ChatMembership
Chat "1" -up-> "0..*" ChatMembership

'' to Message
User "1" --> "0..*" Message : Sends >
Chat "1" -right-> "0..*" Message : Holds >
Message "1" --> "0..1" Attachment : Contains >
Message "0..*" --> "0..1" Message : Replies to >

'' with Enumerations
ServiceCredentials "0..*" ..> "1" ServiceType
ChatMembership "0..*" .right.> "1" ChatMemberStatus
GroupChat "0..*" -left-> "1" GroupVisibility

'' Misc
Person "1" --> "0..*" ServiceCredentials : Has stored
User "1" --> "1" UserProfile
GroupChat "1" -up-> "1" ChatProfile

note right of Profile: public accessible infos
@enduml
