@startuml chat-usecase
skinparam monochrome true
left to right direction

' actors
actor "User" as u
actor "Person" as p
' note "Bot has no special usecases" as b
node "Partner Service" as s

' actor hierarchy
u <|-left- p

' use cases
package "de.othr.st.bib48218.chat" {
  usecase "Login user" as oUC1
  usecase "Logout user" as oUC2
  usecase "Register user" as oUC3
  usecase "Change user profile" as oUC4

  usecase "Send message" as mUC
  ' Chating use cases
  usecase "Create group chat" as cUC1
  usecase "Leave group chat" as cUC2
  usecase "Change profile of group chat" as cUC3
  usecase "Change group chat membership of user" as cUC4
  usecase "Invite user to group" as cUC5
  usecase "Join group chat" as cUC6
  ' Connecting to partners use cases
  usecase "Store (partner) service account credentials" as pUC
}

'  link actor User with use cases
p --> oUC1
p --> oUC2
p --> oUC3
p --> oUC4
p --> cUC3
p --> cUC6
s --> mUC
u --> mUC
p --> cUC1
u --> cUC2
u --> cUC4
u --> cUC5
p --> pUC
@enduml
