@startuml chat-domain
' classes in alphabetical order
abstract class Attachment {
    size : int
    name : String
    mime_type : String
}

abstract class Chat <<IdEntity>> {
    title : String
    description : String
    image : File
    owner : Person
}

class ChatMembership {
    user : User
    chat : Chat
    status : ChatMemberStatus
}

enum ChatMemberStatus {
    Administrator
    Member
    Restricted
    Left
    Kicked
}

class GroupChat {
    getInvitationLink()
}

class Login {
    service : String
    login_token : String
}

class Message <<IdEntity>> {
    timestamp : Datetime
    author : User
    chat : Chat
    reply_to : Message
}

class Person {
    first_name : String
    last_name : String
    country : String
    email : String
    logins : Login
}

class PrivateChat

enum Service {
    Webshop
    Bank
    Payment
}

abstract class User <<IdEntity>> {
    username : String
    password : String
    profil_image : File
}

' Inheritance
'' Chat inheritance
Chat <|-- PrivateChat
Chat <|-- GroupChat
Chat <|-- Channel

'' Attachment inheritance
Attachment <|-- Video
Attachment <|-- Image
Attachment <|-- Voice
Attachment <|-- Document

'' Person inheritance
Person -|> User
User <|- Bot

' Relations
'' to Chat
Person "1" *--> "*" Chat : owner >
User "*" o--> "*" Chat : member >
(User, Chat) .. ChatMembership

'' to Message
User "1" --> "*" Message : sends >
Message "*" -- "1" Chat
Message "1" --> "0..1" Attachment : includes >

'' with Enumerations
Login .left.> Service
ChatMembership ..> ChatMemberStatus

'' Misc
Login "*" <- "1" Person
@enduml
