@startuml chat-component
skinparam monochrome true
' Presentation Layer
package "Presentation" {
    [ChatApp]
}

' Busines (Logic) Layer
package "Business" {
    [UserService] -up- IFUserService
    [ChatService] -up- IFChatService
    [MessageService] -up- IFMessageService
    [MessageService] -up- IFSendMessage
}

' Persistence Layer
package "Persistence" {
    [UserRepository] -up- IFUserRepository
    [ChatRepository] -up- IFChatRepository
    [MessageRepository] -up- IFMessageRepository
}

' Connect presentation layer to busines layer
[ChatApp] .down.( IFUserService
[ChatApp] .down.( IFChatService
[ChatApp] .down.( IFMessageService

' Connect business layer to persistence layer
[UserService] .down.( IFUserRepository
[ChatService] .down.( IFChatRepository
[MessageService] .down.( IFMessageRepository
@enduml
