@startuml chat
' Presentation Layer
package "Presentation" {
    component "Webapplikation" as app
}

' Busines (Logic) Layer
package "Business" {
    component "UserService" as US
    component "ChatService" as CS
    component "MessageService" as MS

    interface "IFUserService" as IFUS
    interface "IFChatService" as IFCS
    interface "IFMessageService" as IFMS

    US -up- IFUS
    CS -up- IFCS
    MS -up- IFMS
}

' Persistence Layer
package "Persistence" {
    node "UserRepository" as UR
    node "ChatRepository" as CR
    node "MessageRepository" as MR

    interface "IFUserRepository" as IFUR
    interface "IFChatRepository" as IFCR
    interface "IFMessageRepository" as IFMR

    UR -up- IFUR
    CR -up- IFCR
    MR -up- IFMR
}

' Database Layer
package "Database" {
    database "MySQL" as db
}

' Connect presentation layer to busines layer
app .down.( IFUS
app .down.( IFCS
app .down.( IFMS

' Connect business layer to persistence layer
US .down.( IFUR
CS .down.( IFCR
MS .down.( IFMR

' Connect persistence layer to database layer
UR .down.> db
CR .down.> db
MR .down.> db
@enduml
