name: Java Test CI with Maven

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SPRING_USER_PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Install local JAR
      run: mvn install:install-file -Dfile=lib/com.othr.swvigopay-0.0.1SNAPSHOT.jar -DgroupId=com.othr -DartifactId=swvigopay -Dversion=0.0.1SNAPSHOT -Dpackaging=jar -DgeneratePom=true
    - name: Build Package
      run: mvn -B clean package -DskipTests
    - name: Verify
      run: mvn -B clean verify
